In [1]:
pip install boto3

Requirement already satisfied: boto3 in c:\users\u\anaconda3\lib\site-packages (1.42.73)
Requirement already satisfied: botocore<1.43.0,>=1.42.73 in c:\users\u\anaconda3\lib\site-packages (from boto3) (1.42.73)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\u\anaconda3\lib\site-packages (from boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\u\anaconda3\lib\site-packages (from boto3) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\u\anaconda3\lib\site-packages (from botocore<1.43.0,>=1.42.73->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\u\anaconda3\lib\site-packages (from botocore<1.43.0,>=1.42.73->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\u\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.73->boto3) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import boto3
import pandas as pd
print("Module Loaded")

Module Loaded

In [3]:

s3 = boto3.resource(
    service_name='s3',
    region_name='ap-south-1',
    aws_access_key_id='AKIA2W62MLBQRF52HWUA',
    aws_secret_access_key='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'
)

print("DONE")

DONE

In [4]:
for i in s3.buckets.all():
    print(i)
    print(i.name)

s3.Bucket(name='aws-learn-bucket-s3-information')
aws-learn-bucket-s3-information
s3.Bucket(name='header-s3-demo-bucket')
header-s3-demo-bucket
s3.Bucket(name='my-new-bucket-6204')
my-new-bucket-6204

In [5]:
s3.buckets.all()

s3.bucketsCollection(s3.ServiceResource(), s3.Bucket)

In [6]:
file = s3.Bucket('aws-learn-bucket-s3-information').Object('players.csv').get()

In [7]:
file

{'ResponseMetadata': {'RequestId': 'B1EB90PFX19N3QNG',
  'HostId': 'OTPdZV9q/t03OjfERRdudsSP3KRCqOQWAY0MbR5whSwEMCyPQ8JabfkZbpuP0lgw6citPCBuNic=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'OTPdZV9q/t03OjfERRdudsSP3KRCqOQWAY0MbR5whSwEMCyPQ8JabfkZbpuP0lgw6citPCBuNic=',
   'x-amz-request-id': 'B1EB90PFX19N3QNG',
   'date': 'Sat, 21 Mar 2026 12:29:53 GMT',
   'last-modified': 'Sat, 21 Mar 2026 07:48:23 GMT',
   'etag': '"947bf323ab0a5cd0e2150aa9160b1eee"',
   'x-amz-checksum-crc64nvme': '7c2762suprQ=',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'x-amz-server-side-encryption': 'AES256',
   'accept-ranges': 'bytes',
   'content-type': 'text/csv',
   'content-length': '617',
   'server': 'AmazonS3'},
  'RetryAttempts': 1},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 3, 21, 7, 48, 23, tzinfo=tzutc()),
 'ContentLength': 617,
 'ETag': '"947bf323ab0a5cd0e2150aa9160b1eee"',
 'ChecksumCRC64NVME': '7c2762suprQ=',
 'ChecksumType': 'FULL_OBJECT',
 'ContentType': 'text/csv',
 'ServerSideEncryption': 'AES256',
 'Metadata': {},
 'Body': <botocore.response.StreamingBody at 0x1b287f2e800>}

In [8]:
bucket = s3.Bucket('aws-learn-bucket-s3-information')

In [9]:
for i in bucket.objects.all():
    print(i)

s3.ObjectSummary(bucket_name='aws-learn-bucket-s3-information', key='players.csv')

In [10]:
for i in bucket.objects.all():
    print(i.key)

players.csv

In [11]:
file

{'ResponseMetadata': {'RequestId': 'B1EB90PFX19N3QNG',
  'HostId': 'OTPdZV9q/t03OjfERRdudsSP3KRCqOQWAY0MbR5whSwEMCyPQ8JabfkZbpuP0lgw6citPCBuNic=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'OTPdZV9q/t03OjfERRdudsSP3KRCqOQWAY0MbR5whSwEMCyPQ8JabfkZbpuP0lgw6citPCBuNic=',
   'x-amz-request-id': 'B1EB90PFX19N3QNG',
   'date': 'Sat, 21 Mar 2026 12:29:53 GMT',
   'last-modified': 'Sat, 21 Mar 2026 07:48:23 GMT',
   'etag': '"947bf323ab0a5cd0e2150aa9160b1eee"',
   'x-amz-checksum-crc64nvme': '7c2762suprQ=',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'x-amz-server-side-encryption': 'AES256',
   'accept-ranges': 'bytes',
   'content-type': 'text/csv',
   'content-length': '617',
   'server': 'AmazonS3'},
  'RetryAttempts': 1},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 3, 21, 7, 48, 23, tzinfo=tzutc()),
 'ContentLength': 617,
 'ETag': '"947bf323ab0a5cd0e2150aa9160b1eee"',
 'ChecksumCRC64NVME': '7c2762suprQ=',
 'ChecksumType': 'FULL_OBJECT',
 'ContentType': 'text/csv',
 'ServerSideEncryption': 'AES256',
 'Metadata': {},
 'Body': <botocore.response.StreamingBody at 0x1b287f2e800>}

In [12]:
df = pd.read_csv(file['Body'])

In [13]:
df

,PlayerID,Name,Age,Team,Role,Matches,Runs,Wickets,StrikeRate,Country
0,1,Rohit Sharma,36,MI,Batsman,250,9800,0,130.5,India
1,2,Virat Kohli,35,RCB,Batsman,260,12000,4,135.2,India
2,3,MS Dhoni,42,CSK,Wicketkeeper,250,5100,0,126.3,India
3,4,Hardik Pandya,31,GT,All-rounder,130,2300,50,145.7,India
4,5,KL Rahul,32,LSG,Batsman,150,6000,0,134.6,India
5,6,Jos Buttler,34,RR,Wicketkeeper,120,4000,0,149.8,England
6,7,David Warner,37,DC,Batsman,180,6500,0,140.2,Australia
7,8,Ben Stokes,33,CSK,All-rounder,100,3000,80,142.1,England
8,9,Jasprit Bumrah,31,MI,Bowler,120,200,150,90.0,India
9,10,Rashid Khan,30,GT,Bowler,140,500,180,120.5,Afghanistan

In [14]:
file

{'ResponseMetadata': {'RequestId': 'B1EB90PFX19N3QNG',
  'HostId': 'OTPdZV9q/t03OjfERRdudsSP3KRCqOQWAY0MbR5whSwEMCyPQ8JabfkZbpuP0lgw6citPCBuNic=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'OTPdZV9q/t03OjfERRdudsSP3KRCqOQWAY0MbR5whSwEMCyPQ8JabfkZbpuP0lgw6citPCBuNic=',
   'x-amz-request-id': 'B1EB90PFX19N3QNG',
   'date': 'Sat, 21 Mar 2026 12:29:53 GMT',
   'last-modified': 'Sat, 21 Mar 2026 07:48:23 GMT',
   'etag': '"947bf323ab0a5cd0e2150aa9160b1eee"',
   'x-amz-checksum-crc64nvme': '7c2762suprQ=',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'x-amz-server-side-encryption': 'AES256',
   'accept-ranges': 'bytes',
   'content-type': 'text/csv',
   'content-length': '617',
   'server': 'AmazonS3'},
  'RetryAttempts': 1},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 3, 21, 7, 48, 23, tzinfo=tzutc()),
 'ContentLength': 617,
 'ETag': '"947bf323ab0a5cd0e2150aa9160b1eee"',
 'ChecksumCRC64NVME': '7c2762suprQ=',
 'ChecksumType': 'FULL_OBJECT',
 'ContentType': 'text/csv',
 'ServerSideEncryption': 'AES256',
 'Metadata': {},
 'Body': <botocore.response.StreamingBody at 0x1b287f2e800>}

In [15]:
# How to upload data on AWS

In [16]:
data = {
    "StudentID": [1,2,3,4,5,6,7,8,9,10],
    "Name": ["Amit","Neha","Rahul","Sneha","Arjun","Priya","Karan","Pooja","Ravi","Anjali"],
    "Age": [20,21,22,20,23,21,22,20,23,21],
    "Course": ["B.Tech","B.Tech","B.Sc","B.Com","B.Tech","BBA","B.Tech","B.Sc","B.Com","B.Tech"],
    "Branch": ["CS","IT","Math","Finance","CS","Marketing","IT","Physics","Accounts","CS"],
    "CGPA": [8.5,9.1,7.8,8.2,7.5,8.9,6.9,9.3,7.2,8.7],
    "City": ["Delhi","Mumbai","Pune","Delhi","Chennai","Kolkata","Bangalore","Hyderabad","Jaipur","Delhi"],
    "Gender": ["Male","Female","Male","Female","Male","Female","Male","Female","Male","Female"],
    "Marks": [85,90,75,82,70,88,65,92,72,86],
    "Grade": ["A","A+","B","A","B","A","C","A+","B","A"]
}

In [17]:
stu = pd.DataFrame(data)

In [18]:
stu

,StudentID,Name,Age,Course,Branch,CGPA,City,Gender,Marks,Grade
0,1,Amit,20,B.Tech,CS,8.5,Delhi,Male,85,A
1,2,Neha,21,B.Tech,IT,9.1,Mumbai,Female,90,A+
2,3,Rahul,22,B.Sc,Math,7.8,Pune,Male,75,B
3,4,Sneha,20,B.Com,Finance,8.2,Delhi,Female,82,A
4,5,Arjun,23,B.Tech,CS,7.5,Chennai,Male,70,B
5,6,Priya,21,BBA,Marketing,8.9,Kolkata,Female,88,A
6,7,Karan,22,B.Tech,IT,6.9,Bangalore,Male,65,C
7,8,Pooja,20,B.Sc,Physics,9.3,Hyderabad,Female,92,A+
8,9,Ravi,23,B.Com,Accounts,7.2,Jaipur,Male,72,B
9,10,Anjali,21,B.Tech,CS,8.7,Delhi,Female,86,A

In [19]:
stu.to_csv("student.csv",index=False)
print("Done")

Done

In [20]:
s3.Bucket('aws-learn-bucket-s3-information').upload_file(Filename="student.csv",Key="student.csv")
print("Done")

Done

In [21]:
bucket = s3.buckets.all()

In [22]:
bucket

s3.bucketsCollection(s3.ServiceResource(), s3.Bucket)

In [23]:
for i in bucket:
  print(i)

s3.Bucket(name='aws-learn-bucket-s3-information')
s3.Bucket(name='header-s3-demo-bucket')
s3.Bucket(name='my-new-bucket-6204')

In [24]:
bucket = s3.Bucket('aws-learn-bucket-s3-information')
for i in bucket.objects.all():
    print(i)
    print("-----")
    print(i.key)

s3.ObjectSummary(bucket_name='aws-learn-bucket-s3-information', key='players.csv')
-----
players.csv
s3.ObjectSummary(bucket_name='aws-learn-bucket-s3-information', key='student.csv')
-----
student.csv

In [25]:
file = s3.Bucket('aws-learn-bucket-s3-information').Object('student.csv').get()

In [26]:
df = pd.read_csv(file['Body'])

In [27]:
df

,StudentID,Name,Age,Course,Branch,CGPA,City,Gender,Marks,Grade
0,1,Amit,20,B.Tech,CS,8.5,Delhi,Male,85,A
1,2,Neha,21,B.Tech,IT,9.1,Mumbai,Female,90,A+
2,3,Rahul,22,B.Sc,Math,7.8,Pune,Male,75,B
3,4,Sneha,20,B.Com,Finance,8.2,Delhi,Female,82,A
4,5,Arjun,23,B.Tech,CS,7.5,Chennai,Male,70,B
5,6,Priya,21,BBA,Marketing,8.9,Kolkata,Female,88,A
6,7,Karan,22,B.Tech,IT,6.9,Bangalore,Male,65,C
7,8,Pooja,20,B.Sc,Physics,9.3,Hyderabad,Female,92,A+
8,9,Ravi,23,B.Com,Accounts,7.2,Jaipur,Male,72,B
9,10,Anjali,21,B.Tech,CS,8.7,Delhi,Female,86,A

In [28]:
bucket

s3.Bucket(name='aws-learn-bucket-s3-information')

In [29]:
bucket.Object('student.csv').delete()
print("Done")

Done

In [30]:
bucket = s3.buckets.all()
for i in bucket:
  print(i)

s3.Bucket(name='aws-learn-bucket-s3-information')
s3.Bucket(name='header-s3-demo-bucket')
s3.Bucket(name='my-new-bucket-6204')

In [31]:

# s3 = boto3.resource('s3')

# bucket_names = [
#     "myapp-hospital-storage",
#     "mycompany-dev-storage",
#     "tamana-bucket-aws"
# ]

# for bucket_name in bucket_names:
#     bucket = s3.Bucket(bucket_name)
    
#     # Step 1: Delete all objects inside bucket
#     bucket.objects.all().delete()
    
#     # Step 2: Delete bucket
#     bucket.delete()
    
#     print(f"{bucket_name} deleted successfully")

In [32]:
import boto3
from botocore.exceptions import ClientError

s3 = boto3.resource('s3')

bucket_names = [
    "myapp-hospital-storage",
    "mycompany-dev-storage",
    "tamana-bucket-aws"
]

for bucket_name in bucket_names:
    try:
        bucket = s3.Bucket(bucket_name)
        
        # delete all versions (if exist)
        bucket.object_versions.all().delete()
        
        # delete bucket
        bucket.delete()
        
        print(f"{bucket_name} deleted successfully")

    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchBucket':
            print(f"{bucket_name} already deleted or not found")
        else:
            print(f"Error in {bucket_name}: {e}")

myapp-hospital-storage already deleted or not found
mycompany-dev-storage already deleted or not found
tamana-bucket-aws already deleted or not found

In [33]:
for i in s3.buckets.all():
    print(i.name)

aws-learn-bucket-s3-information
header-s3-demo-bucket
my-new-bucket-6204

In [34]:
s3 = boto3.resource('s3')

bucket_name = "my-new-bucket-6204"  #  unique hona chahiye

s3.create_bucket(
    Bucket=bucket_name,
    CreateBucketConfiguration={
        'LocationConstraint': 'ap-south-1'  # Mumbai region
    }
)

print("Bucket created successfully")

BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.

In [ ]:
for i in s3.buckets.all():
    print(i.name)