In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Done")

Done

 | Function   | Use                      | Works On           |
| ---------- | ------------------------ | ------------------ |
| `map()`    | Replace/transform values | Series only        |
| `insert()` | Add new column           | DataFrame          |
| `apply()`  | Custom logic             | Series / DataFrame |

In [13]:
df = pd.DataFrame({
    "name": ["A", "B", "C"],
    "marks": [90, 80, 70]
})

In [14]:
df

  name  marks
0    A     90
1    B     80
2    C     70

In [15]:
mapp = {90:'A+',80:'B+',70:'C+',50:'D+'}

In [16]:
mapp

{90: 'A+', 80: 'B+', 70: 'C+', 50: 'D+'}

In [17]:
df['grade'] = df['marks'].map(mapp)

In [18]:
df

  name  marks grade
0    A     90    A+
1    B     80    B+
2    C     70    C+

In [19]:
df["double_marks"] = df["marks"].apply(lambda x: x * 2)

In [20]:
df

  name  marks grade  double_marks
0    A     90    A+           180
1    B     80    B+           160
2    C     70    C+           140

In [29]:
def result(row):
    if row['marks'] > 80:
        return "PASS";
    else:
        return "FAIL"

In [30]:
df['result'] = df.apply(result,axis=1)

In [31]:
df

  name  marks grade  double_marks result
0    A     90    A+           180   PASS
1    B     80    B+           160   FAIL
2    C     70    C+           140   FAIL

In [32]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Rahul", "Amit", "Neha"],
    "marks": [85, 60, 95]
})

In [33]:
def result(row):
    if row["marks"] >= 80:
        return "Pass"
    else:
        return "Fail"

df["result"] = df.apply(result, axis=1)

In [34]:
df

    name  marks result
0  Rahul     85   Pass
1   Amit     60   Fail
2   Neha     95   Pass

In [35]:
df = pd.DataFrame({
    "employee": ["A", "B", "C"],
    "salary": [25000, 50000, 80000]
})

In [36]:
def salrySlip(row):
    if row['salary'] > 35000:
        return "AVG"
    else:
        return "BHAI MEHNAT KR LE"

In [37]:
df

  employee  salary
0        A   25000
1        B   50000
2        C   80000

In [38]:
df['Result'] = df.apply(salrySlip,axis=1)

In [40]:
df

  employee  salary             Result
0        A   25000  BHAI MEHNAT KR LE
1        B   50000                AVG
2        C   80000                AVG

In [41]:
df = pd.DataFrame({
    "player": ["Virat", "Rohit", "Dhoni"],
    "runs": [120, 45, 75]
})

In [42]:
def performance(row):
    if row["runs"] >= 100:
        return "Excellent"
    elif row["runs"] >= 50:
        return "Good"
    else:
        return "Poor"

df["performance"] = df.apply(performance, axis=1)

In [43]:
df

  player  runs performance
0  Virat   120   Excellent
1  Rohit    45        Poor
2  Dhoni    75        Good

In [44]:
import pandas as pd

df = pd.DataFrame({
    "player": ["Virat", "Rohit", "Dhoni", "Gill", "KL Rahul", "Pant", "Hardik", "Surya", "Iyer", "Buttler",
               "Warner", "Faf", "Maxwell", "Jadeja", "Ashwin", "Bumrah", "Shami", "Siraj", "Rashid", "Arshdeep"],

    "team": ["RCB", "MI", "CSK", "GT", "LSG", "DC", "GT", "MI", "KKR", "RR",
             "DC", "RCB", "RCB", "CSK", "RR", "MI", "GT", "RCB", "GT", "PBKS"],

    "role": ["Batsman", "Batsman", "Wicketkeeper", "Batsman", "Wicketkeeper", "Wicketkeeper",
             "All-rounder", "Batsman", "Batsman", "Batsman",
             "Batsman", "Batsman", "All-rounder", "All-rounder", "All-rounder",
             "Bowler", "Bowler", "Bowler", "Bowler", "Bowler"],

    "runs": [120, 45, 75, 30, 95, 110, 60, 85, 55, 140,
             65, 100, 70, 50, 40, 10, 15, 20, 25, 18],

    "balls_faced": [70, 50, 60, 25, 65, 80, 40, 55, 45, 75,
                    50, 60, 45, 35, 30, 12, 18, 20, 22, 15],

    "fours": [10, 5, 6, 3, 8, 12, 5, 9, 6, 15,
              7, 9, 6, 4, 3, 1, 1, 2, 2, 1],

    "sixes": [5, 2, 3, 1, 4, 6, 3, 4, 2, 8,
              3, 5, 4, 2, 1, 0, 0, 1, 1, 0],

    "wickets": [0, 0, 0, 0, 0, 0, 5, 1, 0, 0,
                0, 0, 4, 6, 7, 10, 9, 8, 12, 11],

    "overs": [0, 0, 0, 0, 0, 0, 10, 5, 0, 0,
              0, 0, 8, 12, 15, 20, 18, 17, 20, 19],

    "economy": [0, 0, 0, 0, 0, 0, 7.5, 8.0, 0, 0,
                0, 0, 8.5, 7.0, 6.8, 6.5, 6.9, 7.2, 6.3, 7.1],

    "matches": [5]*20,

    "catches": [3, 2, 5, 1, 2, 4, 3, 2, 2, 1,
                2, 2, 3, 4, 3, 1, 1, 2, 2, 1]
})

In [45]:
df

,player,team,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches
0,Virat,RCB,Batsman,120,70,10,5,0,0,0.0,5,3
1,Rohit,MI,Batsman,45,50,5,2,0,0,0.0,5,2
2,Dhoni,CSK,Wicketkeeper,75,60,6,3,0,0,0.0,5,5
3,Gill,GT,Batsman,30,25,3,1,0,0,0.0,5,1
4,KL Rahul,LSG,Wicketkeeper,95,65,8,4,0,0,0.0,5,2
5,Pant,DC,Wicketkeeper,110,80,12,6,0,0,0.0,5,4
6,Hardik,GT,All-rounder,60,40,5,3,5,10,7.5,5,3
7,Surya,MI,Batsman,85,55,9,4,1,5,8.0,5,2
8,Iyer,KKR,Batsman,55,45,6,2,0,0,0.0,5,2
9,Buttler,RR,Batsman,140,75,15,8,0,0,0.0,5,1
10,Warner,DC,Batsman,65,50,7,3,0,0,0.0,5,2
11,Faf,RCB,Batsman,100,60,9,5,0,0,0.0,5,2
12,Maxwell,RCB,All-rounder,70,45,6,4,4,8,8.5,5,3
13,Jadeja,CSK,All-rounder,50,35,4,2,6,12,7.0,5,4
14,Ashwin,RR,All-rounder,40,30,3,1,7,15,6.8,5,3
15,Bumrah,MI,Bowler,10,12,1,0,10,20,6.5,5,1
16,Shami,GT,Bowler,15,18,1,0,9,18,6.9,5,1
17,Siraj,RCB,Bowler,20,20,2,1,8,17,7.2,5,2
18,Rashid,GT,Bowler,25,22,2,1,12,20,6.3,5,2
19,Arshdeep,PBKS,Bowler,18,15,1,0,11,19,7.1,5,1

In [50]:
df["strike_rate"] = (df["runs"] / df["balls_faced"]) * 100

In [51]:
df

,player,team,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches,strike_rate
0,Virat,RCB,Batsman,120,70,10,5,0,0,0.0,5,3,171.428571
1,Rohit,MI,Batsman,45,50,5,2,0,0,0.0,5,2,90.000000
2,Dhoni,CSK,Wicketkeeper,75,60,6,3,0,0,0.0,5,5,125.000000
3,Gill,GT,Batsman,30,25,3,1,0,0,0.0,5,1,120.000000
4,KL Rahul,LSG,Wicketkeeper,95,65,8,4,0,0,0.0,5,2,146.153846
5,Pant,DC,Wicketkeeper,110,80,12,6,0,0,0.0,5,4,137.500000
6,Hardik,GT,All-rounder,60,40,5,3,5,10,7.5,5,3,150.000000
7,Surya,MI,Batsman,85,55,9,4,1,5,8.0,5,2,154.545455
8,Iyer,KKR,Batsman,55,45,6,2,0,0,0.0,5,2,122.222222
9,Buttler,RR,Batsman,140,75,15,8,0,0,0.0,5,1,186.666667
10,Warner,DC,Batsman,65,50,7,3,0,0,0.0,5,2,130.000000
11,Faf,RCB,Batsman,100,60,9,5,0,0,0.0,5,2,166.666667
12,Maxwell,RCB,All-rounder,70,45,6,4,4,8,8.5,5,3,155.555556
13,Jadeja,CSK,All-rounder,50,35,4,2,6,12,7.0,5,4,142.857143
14,Ashwin,RR,All-rounder,40,30,3,1,7,15,6.8,5,3,133.333333
15,Bumrah,MI,Bowler,10,12,1,0,10,20,6.5,5,1,83.333333
16,Shami,GT,Bowler,15,18,1,0,9,18,6.9,5,1,83.333333
17,Siraj,RCB,Bowler,20,20,2,1,8,17,7.2,5,2,100.000000
18,Rashid,GT,Bowler,25,22,2,1,12,20,6.3,5,2,113.636364
19,Arshdeep,PBKS,Bowler,18,15,1,0,11,19,7.1,5,1,120.000000

In [52]:
def impact(row):
    if row["runs"] > 100 or row["wickets"] > 8:
        return "Match Winner"
    elif row["runs"] > 50 or row["wickets"] > 4:
        return "Good"
    else:
        return "Average"

In [53]:
df

,player,team,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches,strike_rate
0,Virat,RCB,Batsman,120,70,10,5,0,0,0.0,5,3,171.428571
1,Rohit,MI,Batsman,45,50,5,2,0,0,0.0,5,2,90.000000
2,Dhoni,CSK,Wicketkeeper,75,60,6,3,0,0,0.0,5,5,125.000000
3,Gill,GT,Batsman,30,25,3,1,0,0,0.0,5,1,120.000000
4,KL Rahul,LSG,Wicketkeeper,95,65,8,4,0,0,0.0,5,2,146.153846
5,Pant,DC,Wicketkeeper,110,80,12,6,0,0,0.0,5,4,137.500000
6,Hardik,GT,All-rounder,60,40,5,3,5,10,7.5,5,3,150.000000
7,Surya,MI,Batsman,85,55,9,4,1,5,8.0,5,2,154.545455
8,Iyer,KKR,Batsman,55,45,6,2,0,0,0.0,5,2,122.222222
9,Buttler,RR,Batsman,140,75,15,8,0,0,0.0,5,1,186.666667
10,Warner,DC,Batsman,65,50,7,3,0,0,0.0,5,2,130.000000
11,Faf,RCB,Batsman,100,60,9,5,0,0,0.0,5,2,166.666667
12,Maxwell,RCB,All-rounder,70,45,6,4,4,8,8.5,5,3,155.555556
13,Jadeja,CSK,All-rounder,50,35,4,2,6,12,7.0,5,4,142.857143
14,Ashwin,RR,All-rounder,40,30,3,1,7,15,6.8,5,3,133.333333
15,Bumrah,MI,Bowler,10,12,1,0,10,20,6.5,5,1,83.333333
16,Shami,GT,Bowler,15,18,1,0,9,18,6.9,5,1,83.333333
17,Siraj,RCB,Bowler,20,20,2,1,8,17,7.2,5,2,100.000000
18,Rashid,GT,Bowler,25,22,2,1,12,20,6.3,5,2,113.636364
19,Arshdeep,PBKS,Bowler,18,15,1,0,11,19,7.1,5,1,120.000000

In [54]:
df["impact"] = df.apply(impact, axis=1)

In [55]:
df

,player,team,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches,strike_rate,impact
0,Virat,RCB,Batsman,120,70,10,5,0,0,0.0,5,3,171.428571,Match Winner
1,Rohit,MI,Batsman,45,50,5,2,0,0,0.0,5,2,90.000000,Average
2,Dhoni,CSK,Wicketkeeper,75,60,6,3,0,0,0.0,5,5,125.000000,Good
3,Gill,GT,Batsman,30,25,3,1,0,0,0.0,5,1,120.000000,Average
4,KL Rahul,LSG,Wicketkeeper,95,65,8,4,0,0,0.0,5,2,146.153846,Good
5,Pant,DC,Wicketkeeper,110,80,12,6,0,0,0.0,5,4,137.500000,Match Winner
6,Hardik,GT,All-rounder,60,40,5,3,5,10,7.5,5,3,150.000000,Good
7,Surya,MI,Batsman,85,55,9,4,1,5,8.0,5,2,154.545455,Good
8,Iyer,KKR,Batsman,55,45,6,2,0,0,0.0,5,2,122.222222,Good
9,Buttler,RR,Batsman,140,75,15,8,0,0,0.0,5,1,186.666667,Match Winner
10,Warner,DC,Batsman,65,50,7,3,0,0,0.0,5,2,130.000000,Good
11,Faf,RCB,Batsman,100,60,9,5,0,0,0.0,5,2,166.666667,Good
12,Maxwell,RCB,All-rounder,70,45,6,4,4,8,8.5,5,3,155.555556,Good
13,Jadeja,CSK,All-rounder,50,35,4,2,6,12,7.0,5,4,142.857143,Good
14,Ashwin,RR,All-rounder,40,30,3,1,7,15,6.8,5,3,133.333333,Good
15,Bumrah,MI,Bowler,10,12,1,0,10,20,6.5,5,1,83.333333,Match Winner
16,Shami,GT,Bowler,15,18,1,0,9,18,6.9,5,1,83.333333,Match Winner
17,Siraj,RCB,Bowler,20,20,2,1,8,17,7.2,5,2,100.000000,Good
18,Rashid,GT,Bowler,25,22,2,1,12,20,6.3,5,2,113.636364,Match Winner
19,Arshdeep,PBKS,Bowler,18,15,1,0,11,19,7.1,5,1,120.000000,Match Winner

In [56]:
df.insert(2, "country", ["India"]*20)

In [57]:
df

,player,team,country,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches,strike_rate,impact
0,Virat,RCB,India,Batsman,120,70,10,5,0,0,0.0,5,3,171.428571,Match Winner
1,Rohit,MI,India,Batsman,45,50,5,2,0,0,0.0,5,2,90.000000,Average
2,Dhoni,CSK,India,Wicketkeeper,75,60,6,3,0,0,0.0,5,5,125.000000,Good
3,Gill,GT,India,Batsman,30,25,3,1,0,0,0.0,5,1,120.000000,Average
4,KL Rahul,LSG,India,Wicketkeeper,95,65,8,4,0,0,0.0,5,2,146.153846,Good
5,Pant,DC,India,Wicketkeeper,110,80,12,6,0,0,0.0,5,4,137.500000,Match Winner
6,Hardik,GT,India,All-rounder,60,40,5,3,5,10,7.5,5,3,150.000000,Good
7,Surya,MI,India,Batsman,85,55,9,4,1,5,8.0,5,2,154.545455,Good
8,Iyer,KKR,India,Batsman,55,45,6,2,0,0,0.0,5,2,122.222222,Good
9,Buttler,RR,India,Batsman,140,75,15,8,0,0,0.0,5,1,186.666667,Match Winner
10,Warner,DC,India,Batsman,65,50,7,3,0,0,0.0,5,2,130.000000,Good
11,Faf,RCB,India,Batsman,100,60,9,5,0,0,0.0,5,2,166.666667,Good
12,Maxwell,RCB,India,All-rounder,70,45,6,4,4,8,8.5,5,3,155.555556,Good
13,Jadeja,CSK,India,All-rounder,50,35,4,2,6,12,7.0,5,4,142.857143,Good
14,Ashwin,RR,India,All-rounder,40,30,3,1,7,15,6.8,5,3,133.333333,Good
15,Bumrah,MI,India,Bowler,10,12,1,0,10,20,6.5,5,1,83.333333,Match Winner
16,Shami,GT,India,Bowler,15,18,1,0,9,18,6.9,5,1,83.333333,Match Winner
17,Siraj,RCB,India,Bowler,20,20,2,1,8,17,7.2,5,2,100.000000,Good
18,Rashid,GT,India,Bowler,25,22,2,1,12,20,6.3,5,2,113.636364,Match Winner
19,Arshdeep,PBKS,India,Bowler,18,15,1,0,11,19,7.1,5,1,120.000000,Match Winner

In [58]:
team_map = {
    "RCB": "Royal Challengers Bangalore",
    "MI": "Mumbai Indians",
    "CSK": "Chennai Super Kings",
    "GT": "Gujarat Titans",
    "LSG": "Lucknow Super Giants",
    "DC": "Delhi Capitals",
    "KKR": "Kolkata Knight Riders",
    "RR": "Rajasthan Royals",
    "PBKS": "Punjab Kings"
}

In [59]:
df["team_full"] = df["team"].map(team_map)

In [60]:
df

,player,team,country,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches,strike_rate,impact,team_full
0,Virat,RCB,India,Batsman,120,70,10,5,0,0,0.0,5,3,171.428571,Match Winner,Royal Challengers Bangalore
1,Rohit,MI,India,Batsman,45,50,5,2,0,0,0.0,5,2,90.000000,Average,Mumbai Indians
2,Dhoni,CSK,India,Wicketkeeper,75,60,6,3,0,0,0.0,5,5,125.000000,Good,Chennai Super Kings
3,Gill,GT,India,Batsman,30,25,3,1,0,0,0.0,5,1,120.000000,Average,Gujarat Titans
4,KL Rahul,LSG,India,Wicketkeeper,95,65,8,4,0,0,0.0,5,2,146.153846,Good,Lucknow Super Giants
5,Pant,DC,India,Wicketkeeper,110,80,12,6,0,0,0.0,5,4,137.500000,Match Winner,Delhi Capitals
6,Hardik,GT,India,All-rounder,60,40,5,3,5,10,7.5,5,3,150.000000,Good,Gujarat Titans
7,Surya,MI,India,Batsman,85,55,9,4,1,5,8.0,5,2,154.545455,Good,Mumbai Indians
8,Iyer,KKR,India,Batsman,55,45,6,2,0,0,0.0,5,2,122.222222,Good,Kolkata Knight Riders
9,Buttler,RR,India,Batsman,140,75,15,8,0,0,0.0,5,1,186.666667,Match Winner,Rajasthan Royals
10,Warner,DC,India,Batsman,65,50,7,3,0,0,0.0,5,2,130.000000,Good,Delhi Capitals
11,Faf,RCB,India,Batsman,100,60,9,5,0,0,0.0,5,2,166.666667,Good,Royal Challengers Bangalore
12,Maxwell,RCB,India,All-rounder,70,45,6,4,4,8,8.5,5,3,155.555556,Good,Royal Challengers Bangalore
13,Jadeja,CSK,India,All-rounder,50,35,4,2,6,12,7.0,5,4,142.857143,Good,Chennai Super Kings
14,Ashwin,RR,India,All-rounder,40,30,3,1,7,15,6.8,5,3,133.333333,Good,Rajasthan Royals
15,Bumrah,MI,India,Bowler,10,12,1,0,10,20,6.5,5,1,83.333333,Match Winner,Mumbai Indians
16,Shami,GT,India,Bowler,15,18,1,0,9,18,6.9,5,1,83.333333,Match Winner,Gujarat Titans
17,Siraj,RCB,India,Bowler,20,20,2,1,8,17,7.2,5,2,100.000000,Good,Royal Challengers Bangalore
18,Rashid,GT,India,Bowler,25,22,2,1,12,20,6.3,5,2,113.636364,Match Winner,Gujarat Titans
19,Arshdeep,PBKS,India,Bowler,18,15,1,0,11,19,7.1,5,1,120.000000,Match Winner,Punjab Kings

In [61]:
def rating(runs):
    if runs >= 100:
        return "🔥 Excellent"
    elif runs >= 50:
        return "👍 Good"
    else:
        return "😐 Average"

df["rating"] = df["runs"].map(rating)

In [62]:
df

,player,team,country,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches,strike_rate,impact,team_full,rating
0,Virat,RCB,India,Batsman,120,70,10,5,0,0,0.0,5,3,171.428571,Match Winner,Royal Challengers Bangalore,🔥 Excellent
1,Rohit,MI,India,Batsman,45,50,5,2,0,0,0.0,5,2,90.000000,Average,Mumbai Indians,😐 Average
2,Dhoni,CSK,India,Wicketkeeper,75,60,6,3,0,0,0.0,5,5,125.000000,Good,Chennai Super Kings,👍 Good
3,Gill,GT,India,Batsman,30,25,3,1,0,0,0.0,5,1,120.000000,Average,Gujarat Titans,😐 Average
4,KL Rahul,LSG,India,Wicketkeeper,95,65,8,4,0,0,0.0,5,2,146.153846,Good,Lucknow Super Giants,👍 Good
5,Pant,DC,India,Wicketkeeper,110,80,12,6,0,0,0.0,5,4,137.500000,Match Winner,Delhi Capitals,🔥 Excellent
6,Hardik,GT,India,All-rounder,60,40,5,3,5,10,7.5,5,3,150.000000,Good,Gujarat Titans,👍 Good
7,Surya,MI,India,Batsman,85,55,9,4,1,5,8.0,5,2,154.545455,Good,Mumbai Indians,👍 Good
8,Iyer,KKR,India,Batsman,55,45,6,2,0,0,0.0,5,2,122.222222,Good,Kolkata Knight Riders,👍 Good
9,Buttler,RR,India,Batsman,140,75,15,8,0,0,0.0,5,1,186.666667,Match Winner,Rajasthan Royals,🔥 Excellent
10,Warner,DC,India,Batsman,65,50,7,3,0,0,0.0,5,2,130.000000,Good,Delhi Capitals,👍 Good
11,Faf,RCB,India,Batsman,100,60,9,5,0,0,0.0,5,2,166.666667,Good,Royal Challengers Bangalore,🔥 Excellent
12,Maxwell,RCB,India,All-rounder,70,45,6,4,4,8,8.5,5,3,155.555556,Good,Royal Challengers Bangalore,👍 Good
13,Jadeja,CSK,India,All-rounder,50,35,4,2,6,12,7.0,5,4,142.857143,Good,Chennai Super Kings,👍 Good
14,Ashwin,RR,India,All-rounder,40,30,3,1,7,15,6.8,5,3,133.333333,Good,Rajasthan Royals,😐 Average
15,Bumrah,MI,India,Bowler,10,12,1,0,10,20,6.5,5,1,83.333333,Match Winner,Mumbai Indians,😐 Average
16,Shami,GT,India,Bowler,15,18,1,0,9,18,6.9,5,1,83.333333,Match Winner,Gujarat Titans,😐 Average
17,Siraj,RCB,India,Bowler,20,20,2,1,8,17,7.2,5,2,100.000000,Good,Royal Challengers Bangalore,😐 Average
18,Rashid,GT,India,Bowler,25,22,2,1,12,20,6.3,5,2,113.636364,Match Winner,Gujarat Titans,😐 Average
19,Arshdeep,PBKS,India,Bowler,18,15,1,0,11,19,7.1,5,1,120.000000,Match Winner,Punjab Kings,😐 Average

In [63]:
role_map = {
    "Batsman": "Batting Specialist",
    "Bowler": "Bowling Specialist",
    "All-rounder": "All Rounder",
    "Wicketkeeper": "WK-Batsman"
}

df["role_type"] = df["role"].map(role_map)

In [64]:
df

,player,team,country,role,runs,balls_faced,fours,sixes,wickets,overs,economy,matches,catches,strike_rate,impact,team_full,rating,role_type
0,Virat,RCB,India,Batsman,120,70,10,5,0,0,0.0,5,3,171.428571,Match Winner,Royal Challengers Bangalore,🔥 Excellent,Batting Specialist
1,Rohit,MI,India,Batsman,45,50,5,2,0,0,0.0,5,2,90.000000,Average,Mumbai Indians,😐 Average,Batting Specialist
2,Dhoni,CSK,India,Wicketkeeper,75,60,6,3,0,0,0.0,5,5,125.000000,Good,Chennai Super Kings,👍 Good,WK-Batsman
3,Gill,GT,India,Batsman,30,25,3,1,0,0,0.0,5,1,120.000000,Average,Gujarat Titans,😐 Average,Batting Specialist
4,KL Rahul,LSG,India,Wicketkeeper,95,65,8,4,0,0,0.0,5,2,146.153846,Good,Lucknow Super Giants,👍 Good,WK-Batsman
5,Pant,DC,India,Wicketkeeper,110,80,12,6,0,0,0.0,5,4,137.500000,Match Winner,Delhi Capitals,🔥 Excellent,WK-Batsman
6,Hardik,GT,India,All-rounder,60,40,5,3,5,10,7.5,5,3,150.000000,Good,Gujarat Titans,👍 Good,All Rounder
7,Surya,MI,India,Batsman,85,55,9,4,1,5,8.0,5,2,154.545455,Good,Mumbai Indians,👍 Good,Batting Specialist
8,Iyer,KKR,India,Batsman,55,45,6,2,0,0,0.0,5,2,122.222222,Good,Kolkata Knight Riders,👍 Good,Batting Specialist
9,Buttler,RR,India,Batsman,140,75,15,8,0,0,0.0,5,1,186.666667,Match Winner,Rajasthan Royals,🔥 Excellent,Batting Specialist
10,Warner,DC,India,Batsman,65,50,7,3,0,0,0.0,5,2,130.000000,Good,Delhi Capitals,👍 Good,Batting Specialist
11,Faf,RCB,India,Batsman,100,60,9,5,0,0,0.0,5,2,166.666667,Good,Royal Challengers Bangalore,🔥 Excellent,Batting Specialist
12,Maxwell,RCB,India,All-rounder,70,45,6,4,4,8,8.5,5,3,155.555556,Good,Royal Challengers Bangalore,👍 Good,All Rounder
13,Jadeja,CSK,India,All-rounder,50,35,4,2,6,12,7.0,5,4,142.857143,Good,Chennai Super Kings,👍 Good,All Rounder
14,Ashwin,RR,India,All-rounder,40,30,3,1,7,15,6.8,5,3,133.333333,Good,Rajasthan Royals,😐 Average,All Rounder
15,Bumrah,MI,India,Bowler,10,12,1,0,10,20,6.5,5,1,83.333333,Match Winner,Mumbai Indians,😐 Average,Bowling Specialist
16,Shami,GT,India,Bowler,15,18,1,0,9,18,6.9,5,1,83.333333,Match Winner,Gujarat Titans,😐 Average,Bowling Specialist
17,Siraj,RCB,India,Bowler,20,20,2,1,8,17,7.2,5,2,100.000000,Good,Royal Challengers Bangalore,😐 Average,Bowling Specialist
18,Rashid,GT,India,Bowler,25,22,2,1,12,20,6.3,5,2,113.636364,Match Winner,Gujarat Titans,😐 Average,Bowling Specialist
19,Arshdeep,PBKS,India,Bowler,18,15,1,0,11,19,7.1,5,1,120.000000,Match Winner,Punjab Kings,😐 Average,Bowling Specialist

| Feature                | `map()`                               | `apply()`                       |
| ---------------------- | ------------------------------------- | ------------------------------- |
| Kaam kya karta hai     | Values ko replace/transform karta hai | Custom logic apply karta hai    |
| Kis par kaam karta hai | Sirf **Series (1 column)**            | Series + DataFrame (row/column) |
| Multiple columns use?  | Nahi                                |  Haan                          |
| Speed                  |  Fast                                | Thoda slow                   |
| Input                  | dict / function / Series              | function                        |
| Use case               | Mapping, replacing values             | Complex decision making         |

# pd.concat()

- Use: DataFrames ko vertically (upar-niche) ya horizontally (side-by-side) jodne ke liye

In [65]:
df1 = pd.DataFrame({
    "player": ["Virat", "Rohit"],
    "runs": [120, 80]
})

df2 = pd.DataFrame({
    "player": ["Dhoni", "Gill"],
    "runs": [70, 60]
})

In [66]:
df1

  player  runs
0  Virat   120
1  Rohit    80

In [67]:
df2

  player  runs
0  Dhoni    70
1   Gill    60

In [68]:
result = pd.concat([df1,df2])

In [69]:
result

  player  runs
0  Virat   120
1  Rohit    80
0  Dhoni    70
1   Gill    60

# DataFrame.join()

-Use: Index ke basis par join karta hai

In [70]:
df1 = pd.DataFrame({
    "player": ["Virat", "Rohit"]
})

df2 = pd.DataFrame({
    "runs": [120, 80]
})

result = df1.join(df2)
print(result)

  player  runs
0  Virat   120
1  Rohit    80

In [71]:
result

  player  runs
0  Virat   120
1  Rohit    80

# DataFrame.merge()

-Use: SQL join jaisa (common column par)

In [72]:
df1 = pd.DataFrame({
    "player": ["Virat", "Rohit"],
    "team": ["RCB", "MI"]
})

df2 = pd.DataFrame({
    "player": ["Virat", "Rohit"],
    "runs": [120, 80]
})

result = pd.merge(df1, df2, on="player")

In [73]:
result

  player team  runs
0  Virat  RCB   120
1  Rohit   MI    80

# DataFrame.apply()

- Use: Custom logic apply karna

In [74]:
df = pd.DataFrame({
    "player": ["Virat", "Rohit"],
    "runs": [120, 40]
})

def performance(row):
    return "Good" if row["runs"] > 50 else "Bad"

df["performance"] = df.apply(performance, axis=1)

In [75]:
df

  player  runs performance
0  Virat   120        Good
1  Rohit    40         Bad

# DataFrame.insert()

- Use: Specific position par new column add karna

In [76]:
df = pd.DataFrame({
    "player": ["Virat", "Rohit"],
    "runs": [120, 80]
})

df.insert(1, "team", ["RCB", "MI"])

In [77]:
df

  player team  runs
0  Virat  RCB   120
1  Rohit   MI    80

| Function   | Purpose (Kya karta hai)                                              | Syntax                            | Works On         | Key Parameters           | Example Use Case                | Output Type      | Important Notes                         |
| ---------- | -------------------------------------------------------------------- | --------------------------------- | ---------------- | ------------------------ | ------------------------------- | ---------------- | --------------------------------------- |
| `concat()` | Multiple DataFrames ko **stack/join** karta hai (row ya column wise) | `pd.concat([df1, df2], axis=0/1)` | DataFrame        | `axis`, `ignore_index`   | Multiple files ko combine karna | DataFrame        | axis=0 → rows add, axis=1 → columns add |
| `join()`   | **Index ke basis par** do DataFrames join karta hai                  | `df1.join(df2)`                   | DataFrame        | `how`, `on`              | Jab index same ho               | DataFrame        | Default = left join                     |
| `merge()`  | SQL jaisa **common column par join**                                 | `pd.merge(df1, df2, on="col")`    | DataFrame        | `on`, `how`              | Database-style join             | DataFrame        | inner, left, right, outer joins support |
| `apply()`  | Custom function ko **row/column par apply** karta hai                | `df.apply(func, axis=0/1)`        | Series/DataFrame | `axis`                   | Condition / logic lagana        | Series/DataFrame | axis=1 → row-wise, axis=0 → column-wise |
| `insert()` | Specific position par **new column add** karta hai                   | `df.insert(loc, col, values)`     | DataFrame        | `loc`, `column`, `value` | Column ko beech me add karna    | None (in-place)  | Existing column name hua toh error      |